/* DO NOT EDIT, file generated by nestjs-i18n */

import { Path } from 'nestjs-i18n';
export type I18nTranslations = {
  auth: {
    errors: {
      incorrect_email_or_password: string;
      email_already_exists: string;
      email_not_found: string;
      duplicate_email: string;
      invalid_code: string;
      user_not_confirmed: string;
      invalid_refresh_token: string;
      user_already_confirmed: string;
    };
  };
  users: {
    errors: {
      invalid_old_password: string;
      update_password_failed: string;
    };
  };
};
export type I18nPath = Path<I18nTranslations>;
